### ISSUE TITLE
Tableau stuck on Creating Extract (Loading data...) for slow retrieved tables

### ISSUE THREAD

**Issue by guybe87** [CFMTech/Jupytab#41] opened 2020-07-28 13:41 UTC
Hi,

I've noticed that while jupytab works perfectly fine with Tableau for tables which are retrieved quickly, it fails to do so for large tables.
For example:

```
INFO:200 GET /kernel/random_big_table/schema?security_token=random_token (172.17.0.1) 63.51ms
INFO:INFO:tornado.access:200 GET /data?table_name=random_big_table (127.0.0.1) 14083.48ms
INFO:200 GET /kernel/random_notebook/data?table_name=random_big_table&security_token=random_token (172.17.0.1) 14710.38ms
```

Here it takes about 15s to render the table, for some reason Tableau remains stuck on the Loading data screen (inside creating extract) and it never finish this...

Any suggestions?

**Comment by btribonde** [comment] 2020-07-29 21:18
Hello

Just wait for #18 issue completion.

It will switch data transfer from json to something much more efficient. However 15s seems quite fast. What is the size of your table ?

**Comment by guybe87** [comment] 2020-07-30 08:06
The size of my table is (717430, 15), about 140MB as CSV.
Does it make sense that my Tableau stalls on the loading screen?

**Comment by btribonde** [comment] 2020-07-30 08:12
It make sense, it is not as fast as a direct database connection, however jupytab should be able to handle it even in json format.

You could try to do a wget on the data url : your_host:your_port/kernel/random_notebook/data?table_name=random_big_table&security_token=random_token

It will download the data (in json format), and gives you the time used to effectively retrieve the json file, as well as the file size. I would be interested to have this information.

If this is generated data, maybe you could also paste your code below ? I could create a test on big tables for jupytab using a known failed case, and check it's working with the future compressed data format.

**Comment by guybe87** [comment] 2020-07-30 08:32
cURL timing:
    time_namelookup:  0.000001s
       time_connect:  0.000001s
    time_appconnect:  0.000000s
   time_pretransfer:  0.000001s
      time_redirect:  0.000000s
 time_starttransfer:  14.781000s
                    ----------
         time_total:  17.016000s

INFO:200 GET /kernel/random_kernel/data?table_name=random_table&security_token=random_token (172.17.0.1) 15290.64ms

File size is 322MB.

Regarding the code, it's a bit problem to share, because it contains private data of my customers...

**Comment by btribonde** [comment] 2020-07-30 08:46
Everything seems fine, it is a large file but far not enough to break jupytab.

There is a dev mode in the recent versions of Tableau Desktop, that allows to use the chrome console for debugging purpose. I guess the problem is more in the Tableau part than jupytab on: ([https://tableau.github.io/webdataconnector/docs/wdc_debugging.html]).

How long did you wait for the task to complete ?
Also if you are using Windows, you should have a look at the memory used by Tableau Desktop, json format is quite memory hungry and if tableau eats all your available memory it will start to use the swap disk (easy to check in process explorer in windows). Then things start to be ugly, as it takes a lot more time to process the file. There is probably things to do to lower that memory use but I have not yet investigating this area.

**Comment by guybe87** [comment] 2020-07-30 09:52
If by task you mean the loading on the Tableau, it's never complete ...
Also it's important to note that I'm running Tableau Desktop on Windows VM (running on my laptop, with 2GB memory allocated) so memory might be an issue.

I'm not sure regarding the WDC debugging, what to look for exactly...

**Comment by btribonde** [comment] 2020-07-30 09:57
Tableau Desktop on Windows VM (running on my laptop, with 2GB memory allocated)

Almost sure this is the issue in this case. I think it requires something like 5x the json file size as memory.

But will work on this to improve memory usage and speed, we hit the exact same problem in our company (5M rows, 8 columns and several gb as json). But as we have more memory on our desktop this didn't happens as soon as for you.

**Comment by btribonde** [comment] 2020-08-26 14:51
Hello @guybe87, new version 0.9.10 has been deployed to tackle this issue.

**Comment by guybe87** [comment] 2020-08-26 16:03
Hi,

Thanks a lot!
 I've tried the new version and it seems to solve some of the problem.

For medium size dataframes (66MB, retrieved in 3s) it fixed the problem,
but for larger dataframes (e.g. 166MB, retrieved in 7s) it seems Tableau shows an empty result...

Any ideas?

**Comment by btribonde** [comment] 2020-08-26 17:15
Tableau uses a lot of memory so it may still be linked to your VM size. Maybe check that available memory is always below 100%.

By the way the console is much more verbose, this could give you some hints about loading

**Comment by guybe87** [comment] 2020-08-30 09:38
It does seem the VM memory reached 100% so I've increase the memory allocated to it until it peak was ~90% but still the Tableau results in empty response (Memory increase until reaching a peak and then it stops loading and retrieve empty result)

I've used the WDC debugger, and it seems the data is successfully received and digested by the connector but for some reason Tableau doesn't load it... haven't seen anything on console though. Any other ideas?

**Comment by btribonde** [comment] 2020-08-31 07:40
No sorry, the new release solved our scalability problem so I guess there may be something specific to your usecase, but without datas/notebook I will not be able to figure out. Don't hesitate to let me know if you have more details.

**Comment by btribonde** [comment] 2020-09-16 09:13
Latest version (0.9.10+) support large datasource (but requires memory in Tableau desktop), I will close this ticket but do not hesitate to create a new one if you have more input. I will need a failing test notebook however if you want that I investigate your usecase.

**Closed as completed by btribonde** 2020-09-16 09:13 UTC
